import { ReactElement } from "react";

import Link from "next/link";
import localFont from "next/font/local";
import { NextFont } from "next/dist/compiled/@next/font";
import { Poppins } from "next/font/google";

import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";

const headingFont: NextFont = localFont({
  src: "../../../public/fonts/font.woff2",
});

const textFont: NextFont = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

function PrivacyPolicyPage(): ReactElement {
  return (
    <>
      <div className="flex flex-col items-center justify-center py-12 px-4 md:px-10 lg:px-20 text-gray-800 pb-40 pt-40 bg-gradient-to-br from-pink-600 to-yellow-400">
        <div
          className={cn(
            "flex flex-col items-center justify-center space-y-6 text-center",
            headingFont.className
          )}
        >
          <h1 className="text-4xl md:text-6xl font-bold tracking-wide leading-tight text-white">
            Privacy Policy
          </h1>
        </div>
        <div
          className={cn(
            "text-lg md:text-xl lg:text-2xl mt-8 max-w-md md:max-w-2xl text-center text-white",
            textFont.className
          )}
        >
          <p>
            At TaskManagement, safeguarding your privacy is a top priority. We are
            dedicated to ensuring the protection of your personal information and
            upholding your right to privacy. This Privacy Policy outlines how we gather,
            utilize, and share your data when you engage with our task manager services.
            We strongly encourage you to thoroughly review the following information to
            comprehend our procedures concerning your personal data and its management.
            For a comprehensive understanding, please consult our complete Privacy Policy
            document.
          </p>
          <br></br>
          <h2 className="text-3xl font-bold mb-4">Information Collection and Usage</h2>
          <br></br>
          <ul>
            <li>
              Personal details provided during account creation, such as name, email
              address, and contact information.
            </li>
            <li>
              Information generated by your interactions with our platform, including task
              lists, usage patterns, and preferences.
            </li>
            <li>
              Technical data like device information, IP address, browser type, and
              operating system used to access our services.
            </li>
            <li>Payment information necessary to process transactions securely.</li>
          </ul>
          <br></br>
          <h1 className="text-3xl font-bold mb-4">Use of Collected Information</h1>
          <br></br>
          <ul>
            <li>Providing, maintaining, and improving our task manager services.</li>
            <li>
              Personalizing your experience and customizing content to suit your
              preferences.
            </li>
            <li>Facilitating transactions and delivering customer support.</li>
            <li>Analyzing usage trends and enhancing our platform performance.</li>
            <li>
              Complying with legal obligations and protecting against misuse or
              unauthorized access.
            </li>
          </ul>
          <br></br>
          <h1 className="text-3xl font-bold mb-4">Data Sharing and Disclosure</h1>
          <br></br>
          <p>
            Your personal information may be shared with trusted third parties only when
            necessary to deliver our services or as required by law. These entities adhere
            to strict confidentiality and security measures and are prohibited from using
            your data for purposes other than those outlined in this Privacy Policy.
          </p>
          <br></br>
          <h1 className="text-3xl font-bold mb-4">Data Security</h1>
          <br></br>
          <p>
            We employ industry-standard security measures to protect your personal
            information against unauthorized access, alteration, disclosure, or
            destruction. However, please note that no method of data transmission over the
            internet or electronic storage can be entirely secure.
          </p>
          <br></br>
          <h1 className="text-3xl font-bold mb-4">Your Rights</h1>
          <br></br>
          <p>
            You retain certain rights regarding your personal information, including the
            right to access, correct, or delete your data. Please contact us using the
            information provided below to exercise these rights or for any inquiries about
            your information.
          </p>
          <p>This Privacy Policy was last updated on 07/12/2023.</p>
        </div>
      </div>
    </>
  );
}

export default PrivacyPolicyPage;
